name: API Code Analysis

on:
  push:
    branches: [main, beta]
  pull_request:
    branches: [main, beta]
  schedule:
    - cron: '22 4 * * 6'

jobs:
  analyze:
    name: Code QL
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  nodejs_scan:
    name: NodeJS Scan
    needs: [analyze]
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
