name: API Code Analysis & Deploy

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]
    
jobs:
  analyze:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository for code analysis
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
  deploy_staging:
    name: Deploy API to Staging
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/beta' }}
    environment:
      name: Staging
      url: https://staging-sws2apps.herokuapp.com
    runs-on: ubuntu-latest
    needs: [analyze]

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy API to Heroku
        if: ${{ steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/beta' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: staging-sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  deploy_prod:
    name: Deploy API to Production
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/main' }}
    environment:
      name: Production
      url: https://sws2apps.herokuapp.com
    runs-on: ubuntu-latest
    needs: [analyze]

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy API to Heroku
        if: ${{ steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/main' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}