name: production

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy_prod:
    name: Deploy API to Production
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/main' }}
    environment:
      name: Production
      url: https://sws2apps.herokuapp.com
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@5982a02995853159735cb838992248c4f0f16166
        with:
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy API to Heroku
        if: ${{ steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/main' }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Checkout code to merge to Staging
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: beta
          token: ${{ secrets.GH_TOKEN }}

      - name: Rebase changes from main to beta
        run: |
          git rebase origin/main

          git push -f origin beta

      - name: Checkout code to merge to Development
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: alpha
          token: ${{ secrets.GH_TOKEN }}

      - name: Rebase changes from main to alpha
        run: |
          git rebase origin/main

          git push -f origin alpha
