name: CD-DEV-Re

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy_dev:
    name: Deploy API to Development
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/alpha' }}
    environment:
      name: Development
      url: https://dev-sws2apps.herokuapp.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: alpha

      - name: Deploy API to Heroku
        if: ${{ github.ref == 'refs/heads/alpha' }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: dev-sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}
