name: staging-redeploy

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy_staging:
    name: Deploy API to Staging
    if: ${{ github.repository == 'sws2apps/sws2apps-api' && github.ref == 'refs/heads/beta' }}
    environment:
      name: Staging
      url: https://staging-sws2apps.herokuapp.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: beta

      - name: Deploy API to Heroku
        if: ${{ github.ref == 'refs/heads/beta' }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: staging-sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}
